"""initial schema

Revision ID: cb645c5f4c3c
Revises:
Create Date: 2026-08-08 14:37:27.192624+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "cb645c5f4c3c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("metric", sa.String(length=48), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=True),
        sa.Column("operator", sa.String(length=8), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column(
            "channels", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("email_to", sa.String(length=254), nullable=True),
        sa.Column("webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
    )
    with op.batch_alter_table("alert_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alert_rules_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_rules_metric"), ["metric"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_rules_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_rules_owner"), ["owner"], unique=False)
        batch_op.create_index(batch_op.f("ix_alert_rules_subject"), ["subject"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("hashed_key", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "scopes", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key_id"), ["key_id"], unique=True)

    op.create_table(
        "candidate_profiles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=True),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("target_role", sa.String(length=128), nullable=False),
        sa.Column(
            "skills", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("experience_years", sa.Float(), nullable=False),
        sa.Column("seniority", sa.String(length=16), nullable=False),
        sa.Column(
            "countries", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column(
            "cities", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=False),
        sa.Column("remote_preference", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profiles")),
        sa.UniqueConstraint("owner", "label", name="uq_profiles_owner_label"),
    )
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_candidate_profiles_owner"), ["owner"], unique=False)

    op.create_table(
        "companies",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("active_job_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_job_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_companies_country_code"), ["country_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_companies_industry"), ["industry"], unique=False)
        batch_op.create_index(batch_op.f("ix_companies_slug"), ["slug"], unique=True)

    op.create_table(
        "data_quality_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("dimension", sa.String(length=24), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("threshold", sa.Float(), nullable=True),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=32), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_events")),
    )
    with op.batch_alter_table("data_quality_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_data_quality_events_ingestion_run_id"),
            ["ingestion_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_data_quality_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_data_quality_events_source"), ["source"], unique=False)
        batch_op.create_index("ix_dq_events_source_dim", ["source", "dimension"], unique=False)

    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_received", sa.Integer(), nullable=False),
        sa.Column("records_validated", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column("duplicates_detected", sa.Integer(), nullable=False),
        sa.Column("jobs_created", sa.Integer(), nullable=False),
        sa.Column("jobs_updated", sa.Integer(), nullable=False),
        sa.Column("jobs_expired", sa.Integer(), nullable=False),
        sa.Column("fetch_duration_ms", sa.Float(), nullable=False),
        sa.Column("processing_duration_ms", sa.Float(), nullable=False),
        sa.Column("nlp_duration_ms", sa.Float(), nullable=False),
        sa.Column("storage_duration_ms", sa.Float(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingestion_runs_source"), ["source"], unique=False)
        batch_op.create_index(
            "ix_ingestion_runs_source_started", ["source", "started_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ingestion_runs_started_at"), ["started_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ingestion_runs_status"), ["status"], unique=False)

    op.create_table(
        "job_sources",
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_successful_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempted_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_cursor", sa.String(length=512), nullable=True),
        sa.Column("last_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("etag", sa.String(length=256), nullable=True),
        sa.Column("records_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_job_sources")),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("country", sa.String(length=96), nullable=True),
        sa.Column("region", sa.String(length=96), nullable=True),
        sa.Column("city", sa.String(length=96), nullable=True),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("job_count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("country_code", "region", "city", name="uq_locations_geo"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index("ix_locations_country_city", ["country_code", "city"], unique=False)
        batch_op.create_index(batch_op.f("ix_locations_slug"), ["slug"], unique=True)

    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_jobs", sa.Integer(), nullable=False),
        sa.Column("new_jobs", sa.Integer(), nullable=False),
        sa.Column("expired_jobs", sa.Integer(), nullable=False),
        sa.Column("companies_hiring", sa.Integer(), nullable=False),
        sa.Column("remote_share", sa.Float(), nullable=False),
        sa.Column("average_salary", sa.Float(), nullable=True),
        sa.Column("median_salary", sa.Float(), nullable=True),
        sa.Column("data_quality_score", sa.Float(), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_snapshot_date"), ["snapshot_date"], unique=True
        )

    op.create_table(
        "rejected_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_job_id", sa.String(length=256), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("message", sa.String(length=1000), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=True),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("ingestion_run_id", sa.String(length=32), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejected_records")),
    )
    with op.batch_alter_table("rejected_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rejected_records_ingestion_run_id"), ["ingestion_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rejected_records_reason"), ["reason"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rejected_records_rejected_at"), ["rejected_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_rejected_records_source"), ["source"], unique=False)
        batch_op.create_index(
            "ix_rejected_records_source_time", ["source", "rejected_at"], unique=False
        )

    op.create_table(
        "skills",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("parent_slug", sa.String(length=64), nullable=True),
        sa.Column(
            "aliases", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_slug"],
            ["skills.slug"],
            name=op.f("fk_skills_parent_slug_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_skills")),
    )
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skills_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_skills_parent_slug"), ["parent_slug"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_job_id", sa.String(length=256), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=True),
        sa.Column("url_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("normalized_title", sa.String(length=256), nullable=False),
        sa.Column("title_family", sa.String(length=128), nullable=False),
        sa.Column("specialization", sa.String(length=128), nullable=True),
        sa.Column("title_confidence", sa.Float(), nullable=False),
        sa.Column("company_id", sa.String(length=32), nullable=True),
        sa.Column("company_name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("description_snippet", sa.String(length=512), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_raw", sa.String(length=256), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("country", sa.String(length=96), nullable=True),
        sa.Column("region", sa.String(length=96), nullable=True),
        sa.Column("city", sa.String(length=96), nullable=True),
        sa.Column("remote_type", sa.String(length=16), nullable=False),
        sa.Column("employment_type", sa.String(length=24), nullable=False),
        sa.Column("experience_level", sa.String(length=16), nullable=False),
        sa.Column("experience_years_min", sa.Float(), nullable=True),
        sa.Column("experience_years_max", sa.Float(), nullable=True),
        sa.Column("salary_min", sa.Float(), nullable=True),
        sa.Column("salary_max", sa.Float(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("salary_period", sa.String(length=16), nullable=False),
        sa.Column("salary_provenance", sa.String(length=16), nullable=False),
        sa.Column("salary_annual_min", sa.Float(), nullable=True),
        sa.Column("salary_annual_max", sa.Float(), nullable=True),
        sa.Column("salary_confidence", sa.Float(), nullable=False),
        sa.Column("salary_raw", sa.String(length=256), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("duplicate_of", sa.String(length=32), nullable=True),
        sa.Column("duplicate_kind", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "similarity_signature",
            sa.JSON().with_variant(postgresql.JSONB(), "postgresql"),
            nullable=False,
        ),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column(
            "attributes", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1", name=op.f("ck_jobs_quality_score_range")
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name=op.f("ck_jobs_salary_bounds_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_jobs_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["duplicate_of"],
            ["jobs.id"],
            name=op.f("fk_jobs_duplicate_of_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_jobs_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source", "source_job_id", name="uq_jobs_source_identity"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_city"), ["city"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_company_name"), ["company_name"], unique=False)
        batch_op.create_index("ix_jobs_company_status", ["company_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_country_code"), ["country_code"], unique=False)
        batch_op.create_index("ix_jobs_country_status", ["country_code", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_duplicate_of"), ["duplicate_of"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_experience_level"), ["experience_level"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_first_seen_at"), ["first_seen_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_last_seen_at"), ["last_seen_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_normalized_title"), ["normalized_title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_published_at"), ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_remote_type"), ["remote_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_salary_provenance"), ["salary_provenance"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_jobs_segment"), ["segment"], unique=False)
        batch_op.create_index("ix_jobs_segment_status", ["segment", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_jobs_status_first_seen", ["status", "first_seen_at"], unique=False
        )
        batch_op.create_index("ix_jobs_status_published", ["status", "published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_title_family"), ["title_family"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_jobs_url_fingerprint"), ["url_fingerprint"], unique=False
        )

    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.String(length=4000), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "context", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["alert_rules.id"],
            name=op.f("fk_notifications_rule_id_alert_rules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_delivered"), ["delivered"], unique=False)
        batch_op.create_index(
            "ix_notifications_rule_created", ["rule_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_rule_id"), ["rule_id"], unique=False)

    op.create_table(
        "skill_trends",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("skill_slug", sa.String(length=64), nullable=False),
        sa.Column("day", sa.DateTime(timezone=True), nullable=False),
        sa.Column("job_count", sa.Integer(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.Column("moving_average", sa.Float(), nullable=True),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_slug"],
            ["skills.slug"],
            name=op.f("fk_skill_trends_skill_slug_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_trends")),
        sa.UniqueConstraint("skill_slug", "day", name="uq_skill_trends_skill_day"),
    )
    with op.batch_alter_table("skill_trends", schema=None) as batch_op:
        batch_op.create_index("ix_skill_trends_day", ["day"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_skill_trends_skill_slug"), ["skill_slug"], unique=False
        )

    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=32), nullable=True),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_events_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_events")),
    )
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_events_ingestion_run_id"), ["ingestion_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_job_events_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_job_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            "ix_job_events_type_time", ["event_type", "occurred_at"], unique=False
        )

    op.create_table(
        "job_skills",
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("skill_slug", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=32), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_job_skills_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_skills_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_slug"],
            ["skills.slug"],
            name=op.f("fk_job_skills_skill_slug_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "skill_slug", name=op.f("pk_job_skills")),
    )
    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.create_index("ix_job_skills_skill_job", ["skill_slug", "job_id"], unique=False)

    op.create_table(
        "salary_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("min_amount", sa.Float(), nullable=True),
        sa.Column("max_amount", sa.Float(), nullable=True),
        sa.Column("annual_min", sa.Float(), nullable=True),
        sa.Column("annual_max", sa.Float(), nullable=True),
        sa.Column("annual_midpoint", sa.Float(), nullable=True),
        sa.Column("provenance", sa.String(length=16), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("experience_level", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_salary_records_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salary_records")),
    )
    with op.batch_alter_table("salary_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_salary_records_annual_midpoint"), ["annual_midpoint"], unique=False
        )
        batch_op.create_index(
            "ix_salary_records_dims", ["segment", "experience_level", "country_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_salary_records_job_id"), ["job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_salary_records_observed_at"), ["observed_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("salary_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_salary_records_observed_at"))
        batch_op.drop_index(batch_op.f("ix_salary_records_job_id"))
        batch_op.drop_index("ix_salary_records_dims")
        batch_op.drop_index(batch_op.f("ix_salary_records_annual_midpoint"))

    op.drop_table("salary_records")
    with op.batch_alter_table("job_skills", schema=None) as batch_op:
        batch_op.drop_index("ix_job_skills_skill_job")

    op.drop_table("job_skills")
    with op.batch_alter_table("job_events", schema=None) as batch_op:
        batch_op.drop_index("ix_job_events_type_time")
        batch_op.drop_index(batch_op.f("ix_job_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_job_events_job_id"))
        batch_op.drop_index(batch_op.f("ix_job_events_ingestion_run_id"))

    op.drop_table("job_events")
    with op.batch_alter_table("skill_trends", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_trends_skill_slug"))
        batch_op.drop_index("ix_skill_trends_day")

    op.drop_table("skill_trends")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_rule_id"))
        batch_op.drop_index("ix_notifications_rule_created")
        batch_op.drop_index(batch_op.f("ix_notifications_delivered"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_url_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_jobs_title_family"))
        batch_op.drop_index("ix_jobs_status_published")
        batch_op.drop_index("ix_jobs_status_first_seen")
        batch_op.drop_index(batch_op.f("ix_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_jobs_source"))
        batch_op.drop_index("ix_jobs_segment_status")
        batch_op.drop_index(batch_op.f("ix_jobs_segment"))
        batch_op.drop_index(batch_op.f("ix_jobs_salary_provenance"))
        batch_op.drop_index(batch_op.f("ix_jobs_remote_type"))
        batch_op.drop_index(batch_op.f("ix_jobs_published_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_normalized_title"))
        batch_op.drop_index(batch_op.f("ix_jobs_last_seen_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_first_seen_at"))
        batch_op.drop_index(batch_op.f("ix_jobs_experience_level"))
        batch_op.drop_index(batch_op.f("ix_jobs_duplicate_of"))
        batch_op.drop_index("ix_jobs_country_status")
        batch_op.drop_index(batch_op.f("ix_jobs_country_code"))
        batch_op.drop_index(batch_op.f("ix_jobs_content_hash"))
        batch_op.drop_index("ix_jobs_company_status")
        batch_op.drop_index(batch_op.f("ix_jobs_company_name"))
        batch_op.drop_index(batch_op.f("ix_jobs_company_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_city"))

    op.drop_table("jobs")
    with op.batch_alter_table("skills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skills_parent_slug"))
        batch_op.drop_index(batch_op.f("ix_skills_category"))

    op.drop_table("skills")
    with op.batch_alter_table("rejected_records", schema=None) as batch_op:
        batch_op.drop_index("ix_rejected_records_source_time")
        batch_op.drop_index(batch_op.f("ix_rejected_records_source"))
        batch_op.drop_index(batch_op.f("ix_rejected_records_rejected_at"))
        batch_op.drop_index(batch_op.f("ix_rejected_records_reason"))
        batch_op.drop_index(batch_op.f("ix_rejected_records_ingestion_run_id"))

    op.drop_table("rejected_records")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_snapshots_snapshot_date"))

    op.drop_table("market_snapshots")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_locations_slug"))
        batch_op.drop_index("ix_locations_country_city")

    op.drop_table("locations")
    op.drop_table("job_sources")
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_status"))
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_started_at"))
        batch_op.drop_index("ix_ingestion_runs_source_started")
        batch_op.drop_index(batch_op.f("ix_ingestion_runs_source"))

    op.drop_table("ingestion_runs")
    with op.batch_alter_table("data_quality_events", schema=None) as batch_op:
        batch_op.drop_index("ix_dq_events_source_dim")
        batch_op.drop_index(batch_op.f("ix_data_quality_events_source"))
        batch_op.drop_index(batch_op.f("ix_data_quality_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_data_quality_events_ingestion_run_id"))

    op.drop_table("data_quality_events")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_slug"))
        batch_op.drop_index(batch_op.f("ix_companies_industry"))
        batch_op.drop_index(batch_op.f("ix_companies_country_code"))

    op.drop_table("companies")
    with op.batch_alter_table("candidate_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_candidate_profiles_owner"))

    op.drop_table("candidate_profiles")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_key_id"))

    op.drop_table("api_keys")
    with op.batch_alter_table("alert_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alert_rules_subject"))
        batch_op.drop_index(batch_op.f("ix_alert_rules_owner"))
        batch_op.drop_index(batch_op.f("ix_alert_rules_name"))
        batch_op.drop_index(batch_op.f("ix_alert_rules_metric"))
        batch_op.drop_index(batch_op.f("ix_alert_rules_enabled"))

    op.drop_table("alert_rules")
    # ### end Alembic commands ###
