"""Domain models: enums, raw records, the canonical job schema and DTOs."""

from __future__ import annotations

from app.models.alerts import AlertEvaluation, AlertRule, Notification
from app.models.analytics import (
    AnalyticsFilter,
    CompanyHiring,
    EmergingSkill,
    LocationDemand,
    MarketFitResult,
    MarketOverview,
    RemoteBreakdown,
    SalaryStatistics,
    SeniorityBreakdown,
    SkillCooccurrence,
    SkillDemand,
    SkillTrend,
    VolumeSeries,
)
from app.models.enums import (
    AlertChannel,
    AlertMetric,
    ComparisonOperator,
    DuplicateKind,
    EmploymentType,
    EventType,
    ExperienceLevel,
    IngestionStatus,
    JobStatus,
    MarketSegment,
    QualityDimension,
    RejectionReason,
    RemoteType,
    SalaryPeriod,
    SalaryProvenance,
    Scope,
    SkillCategory,
    SourceKind,
    TrendDirection,
    UserRole,
)
from app.models.events import PipelineEvent
from app.models.ingestion import IngestionRun, SourceState
from app.models.job import (
    ExtractedSkill,
    LocationInfo,
    NormalizedJob,
    SalaryInfo,
    TitleAnalysis,
)
from app.models.profiles import CandidateProfile
from app.models.quality import FieldQuality, QualityEvent, QualityReport
from app.models.raw import RawBatch, RawJob, RejectedRecord

__all__ = [
    "AlertChannel",
    "AlertEvaluation",
    "AlertMetric",
    "AlertRule",
    "AnalyticsFilter",
    "CandidateProfile",
    "CompanyHiring",
    "ComparisonOperator",
    "DuplicateKind",
    "EmergingSkill",
    "EmploymentType",
    "EventType",
    "ExperienceLevel",
    "ExtractedSkill",
    "FieldQuality",
    "IngestionRun",
    "IngestionStatus",
    "JobStatus",
    "LocationDemand",
    "LocationInfo",
    "MarketFitResult",
    "MarketOverview",
    "MarketSegment",
    "NormalizedJob",
    "Notification",
    "PipelineEvent",
    "QualityDimension",
    "QualityEvent",
    "QualityReport",
    "RawBatch",
    "RawJob",
    "RejectedRecord",
    "RejectionReason",
    "RemoteBreakdown",
    "RemoteType",
    "SalaryInfo",
    "SalaryPeriod",
    "SalaryProvenance",
    "SalaryStatistics",
    "Scope",
    "SeniorityBreakdown",
    "SkillCategory",
    "SkillCooccurrence",
    "SkillDemand",
    "SkillTrend",
    "SourceKind",
    "SourceState",
    "TitleAnalysis",
    "TrendDirection",
    "UserRole",
    "VolumeSeries",
]
